{% set name = "amuse-framework" %}
{% set version = "2023.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/amusecode/amuse.git
  git_rev: v2023.11.0
  git_depth: 1
  patches:
    - patches/simple_hash_no_test.patch

build:
  number: 0
  string: {{ mpi }}_{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

  skip: true                      # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - git
    - git-lfs
    - make
    - cmake
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
    - gnuconfig                             # [unix]
    # - conda-verify

  host:
    - {{ mpi }}
    - python
    - setuptools
    - setuptools_scm
    - pip
    - wheel
    - pytest
    - docutils
    - mpi4py
    - h5py
    - numpy
    - matplotlib

  run:
    - libgcc-ng                 # [linux]
    - libstdcxx-ng              # [linux]
    - libgfortran5              # [linux]
    - python
    - numpy
    - mpi4py
    - h5py

test:

about:
  home: https://github.com/amusecode/amuse
  summary: Astrophysical Multipurpose Software Environment - Framework
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
